### ISSUE TITLE
Remove login details from commit history

### ISSUE THREAD

**Issue by UjjwalAyyangar** [samyak-jain/competitive-cli#1]
@apuayush Your login details can be seen in the commit history.

One solution to fix it would be :- 
* run "git log" on your terminal and note down the faulty commit.
* force push the new changes on that commit.

<a href="http://samwize.com/2014/01/15/how-to-remove-a-commit-that-is-already-pushed-to-github/"> Check this link </a>

**Comment by apuayush** [comment]
thanx for bringing it to notice..
