### ISSUE TITLE
Post request to submit code ..need help

### ISSUE THREAD

**Issue by apuayush** [samyak-jain/competitive-cli#3]
hey samyak i have some problem in sending POST request to submit portal on codechef... the code text area seems to not taking the code... having a problem need some help.
`payload ={
            'form_build_id': form_build_id,
            'form_token': form_token,
            'form_id': 'problem_submission',
            "language": lang,
            'program': code.read(),
            'problem_code': question_code,
            'op': "Submit"
        }`

in this area in submit function of codechef.py

**Comment by samyak-jain** [comment]
Try adding the following to the payload
`"files[sourcefile]": "", "filename": ""`

**Comment by apuayush** [comment]
added ` file = {
            "files[sourcefile]": open(file_path)
        }
        response = self.codechef_session.post(CodechefSession.codechef_url + '/submit/' + question_code, data=payload, files=file, verify=False)`
issue resolved
